import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Tosin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Peter',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Apple watch series 7',
      category: 'watch',
      image: '/images/watch.jpg',
      countInStock: 10,
      price: 750,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple Watch Series 7 (GPS) 45MM - Abyss green Sport Band',
    },
    {
      name: 'Iphone 13 pro',
      category: 'phone',
      countInStock: 20,
      image: '/images/iphone13.webp',
      price: 1200,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: 'Apple IPhone 13 Pro Max - 256GB, 6GB RAM, 6.7-Inch,(12MP+12MP+12MP) - 5G-Pacific Black',
    },
    {
      name: 'Apple Airpods max',
      category: 'airpods',
      image: '/images/airpod.webp',
      countInStock: 0,
      price: 900,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 17,
      description: 'Apple AirPods Max - Sky Blue',
    },
    {
      name: 'Iphone 12 pro',
      category: 'phone',
      image: '/images/iphone12.webp',
      countInStock: 5,
      price: 999.9,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'Apple IPhone 12 Pro Max - 256GB, 6GB RAM, 6.7-Inch,(10MP+10MP+10MP) - 5G-Pacific Blue',
    },
    {
      name: 'Airpod pro',
      category: 'airpods',
      countInStock: 15,
      image: '/images/airpod2.webp',
      price: 199,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'AirPods Pro With Magsafe Charging Case - Black',
    },
    {
      name: 'Macbook pro 2021',
      category: 'laptops',
      image: '/images/macbook.webp',
      countInStock: 12,
      price: 1999,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'Apple MacBook Pro 14.2" - M1 Pro Chip - 16GB 1TB Space Grey - 2021',
    },
  ],
};

export default data;
