const data = {
  products: [
    {
      _id: '1',
      name: 'Apple watch series 7',
      category: 'watch',
      image: '/images/watch.jpg',
      countInStock: 10,
      price: 75000,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Iphone 13 pro',
      category: 'phone',
      countInStock: 20,
      image: '/images/iphone13.webp',
      price: 700000,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Airpods max',
      category: 'airpods',
      image: '/images/airpod.webp',
      countInStock: 0,
      price: 90000,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Iphone 12 pro',
      category: 'phone',
      image: '/images/iphone12.webp',
      countInStock: 5,
      price: 650000,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Airpod pro',
      category: 'airpods',
      countInStock: 15,
      image: '/images/airpod2.webp',
      price: 110000,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Macbook pro 2021',
      category: 'laptops',
      image: '/images/macbook.webp',
      countInStock: 12,
      price: 1200000,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};

export default data;
